pipeline{
    agent any

    stages{
        stage(deploy) {
            steps {
                sh '''
            		oc project bjxrei-deploy-strategies
			oc start-build greeting-service --follow --wait
		'''
			}
		}
	}
}
